#!/usr/bin/env zsh

# installation
if not type zsh; then 
    sudo apt-get update && sudo apt-get -y install zsh
else
    echo "zsh is already installed"
fi

# Oh My ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Plugins
git clone https://github.com/supercrabtree/k ~/.oh-my-zsh/custom/plugins//k
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions


# Copy Zshrc Reference Template
echo "Starting..."

rm ~/.zshrc
cp ./templates/.zshrc ~/.zshrc

echo "Stopping..."